# Generated by Django 2.2.4 on 2020-08-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clean',
            name='CTY_NM_2',
        ),
        migrations.AddField(
            model_name='clean',
            name='CTY_IMG',
            field=models.CharField(default='img', max_length=200),
        ),
        migrations.AddField(
            model_name='clean',
            name='CTY_NM',
            field=models.CharField(default='cty2', max_length=100),
        ),
    ]
