# Generated by Django 2.2.4 on 2020-09-02 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_upjong'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upjong',
            old_name='WEEK_UPJONG',
            new_name='WEAK_UPJONG',
        ),
    ]
